[package]
name = "hello-rust-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.17"
tokio = { version = "1.32.0", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
